apiVersion: apps/v1
kind: Deployment
metadata:
  name: otl-service
  labels:
    app: otl
spec:
  selector:
    matchLabels:
      app: otl
  replicas: 1
  template:
    metadata:
      labels:
        app: otl
    spec:
      containers:
        - name: otl
          image: lakshankarunathilake/otl-service:v1.3
          ports:
            - name: otl-service
              containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: otl-service
spec:
  selector:
    app: otl
  ports:
    - port: 9000
      targetPort: otl-service